coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5
    patch:
      default:
        target: 70%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes